### ISSUE TITLE
dataset이 없습니다

### ISSUE THREAD

**Issue by laetokang** [KoreanAI2022/2022-Korean-AI-Competition#1]
NSML에 접속해서 데이터셋을 확인한 결과, 기존 NSML로 접속되어 전혀 다른 데이터셋들만 있습니다.
이런 경우 어떻게 해야 하나요?

**Comment by KoreanAI2022** [comment]
안녕하세요, laetokang 참가자님,
2022 한국어 AI 경진대회 운영지원팀입니다.

기존 설치해주셨던 클라이언트를 삭제하시고,
공지에 있는 새로운 NSML 페이지에서 다운 받으신 클라이언트로 재 설치 해주시기 바랍니다.

감사합니다.
2022 한국어 AI 경진대회 운영지원팀

**Comment by KoreanAI2022** [comment]
laetokang 참가자님, 해결되셨다면 close 부탁드리겠습니다.
