### ISSUE TITLE
[Track1] t1-cmd, t1-free 오디오 포멧 문의

### ISSUE THREAD

**Issue by 21jun** [KoreanAI2022/2022-Korean-AI-Competition#2]
안녕하세요.

`t1-cmd`, `t1-free` 의 train set 오디오 포멧이 어떻게 될까요?

우선 mp3 포멧으로 로드해 보았는데, 
```py
speech, sample_rate = torchaudio.load(str(path), format="mp3")
```

몇몇 파일은 torch audio (sox_io) 로 load 했을때, 
```
python: /root/project/build/temp.linux-x86_64-3.8/third_party/sox/src/mad/layer3.c:2633: mad_layer_III: Assertion `stream->md_len + md_len - si.main_data_begin <= (511 + 2048 + 8)' failed.
/bin/bash: line 1:    44 Aborted
```
위 처럼 오류가 발생합니다.

추가로 `t1-free`의 오디오 길이가 비정상적으로 짧은것 같은데 문제가 없는 것인지 확인 부탁드립니다.
ex)

`/data/t1-free/train/train_data/idx_000045` 을 `speech, sample_rate = torchaudio.load(str(path), format="mp3")` 으로 읽었을때, 

데이터 길이 384, 샘플레이트 32000

**Comment by KoreanAI2022** [comment]
안녕하세요, 21jun 참가자님,
2022 한국어 AI 경진대회 운영지원팀입니다.

1. 제공된 음성 데이터는 헤더가 없는 PCM 형식 파일입니다. (signed 16-bit little-endian)
sample rate는 16000Hz이며, Mono(1 channel)로 구성되어 있습니다.

2. idx_000045파일 확인 결과 문제 없이 로드 되는 것을 확인했습니다.

감사합니다.
2022 한국어 AI 경진대회 운영지원팀
