### ISSUE TITLE
run한 session을 강제로 종료할 수 없을까요?

### ISSUE THREAD

**Issue by laetokang** [KoreanAI2022/2022-Korean-AI-Competition#3]
계속 Allocated...라고 떠서 강제로 session을 종료하고 싶은데 
계속 실패한다라고 뜨네요...
이런 경우 해결방법은 없을까요?

**Comment by KoreanAI2022** [comment]
안녕하세요, [laetokang](https://github.com/laetokang) 참가자님
2022 한국어 AI 경진대회 운영지원팀입니다.

nsml 세션 생성시 docker container 생성으로 인해 다소 시간이 소요될 수 있습니다.
세션 삭제가 불가능 하실 경우, CLI를 통해
[nsml rm -f 세션이름] 으로 삭제하실 수 있습니다.


감사합니다.
2022 한국어 AI 경진대회 운영지원팀
