### ISSUE TITLE
nsml teams 명령어와 NSML 홈페이지의 팀명이 일치하는 않는 것으로 보입니다.  

### ISSUE THREAD

**Issue by kimkwangho82** [KoreanAI2022/2022-Korean-AI-Competition#4]
nsml teams 명령어와 NSML 홈페이지의 팀명이 일치하는 않는 것으로 보입니다. 

nsml teams
>> nia1051

(NSML 홈페이지) 
>> KAIC112 

팀명: 뤂가이즈
깃헙 아이디: kimkwangho82

확인 부탁드립니다. 

감사합니다.

**Comment by KoreanAI2022** [comment]
안녕하세요, [kimkwangho82](https://github.com/kimkwangho82)참가자님
2022 한국어 AI 경진대회 운영지원팀입니다.

nsml logout 후 nsml login 으로 재로그인 해 주시고,
동일 오류 발생한 경우 전체 로그를 캡쳐하여 업로드 부탁드리겠습니다.

감사합니다.
2022 한국어 AI 경진대회 운영지원팀

**Comment by kimkwangho82** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1249794/186550846-af96632e-60f6-43c0-a901-9b947d3b7834.png">

**Comment by KoreanAI2022** [comment]
본 대회 NSML CLI 클라이언트는 nsml login 시 
`ncp-cli.nsml.navercorp.com:443` 으로 접속됩니다.

클라이언트 확인 부탁 드립니다.

감사합니다.
2022 한국어 AI 경진대회 운영지원팀

**Comment by kimkwangho82** [comment]
답변 감사드립니다. 

클라이언트 변경해서 접속 완료하였습니다.
